### ISSUE TITLE
Create thumbnail for projects details page

### ISSUE THREAD

**Issue by fardinzam** [acm-ucr/senior-design-website#29]
use the image1.png form the public folder for the thumbnail as a placeholder, we'll work on getting the images soon

<img width="510" alt="Screenshot 2024-01-24 at 12 14 42 AM" src="https://github.com/acm-ucr/senior-design-website/assets/55073341/1da5a8d1-c024-4304-a8ca-f6faead91dbf">

**Comment by brianubyun** [comment]
Based on the figma and the example image, it seems image was cropped to fit a certain size in the project sections page. Not entirely show if how I did is optimal or correct, so let me know.

This is how the website looks: (fullscreen)
![image](https://github.com/acm-ucr/senior-design-website/assets/146309310/393548f3-86f4-48dd-bf8c-ddc9782301c7)


Not full screen:
![image](https://github.com/acm-ucr/senior-design-website/assets/146309310/c74f6cf8-993d-4e5c-b576-c70aa454c9ed)
