### ISSUE TITLE
Make page responsive

### ISSUE THREAD

**Issue by fardinzam** [acm-ucr/senior-design-website#65]
- confirm responsiveness from mobile to extra-wide aspect ratios
<img width="223" alt="Screenshot 2024-02-17 at 12 49 14 AM" src="https://github.com/acm-ucr/senior-design-website/assets/55073341/019099e0-de88-4dc9-be2d-b5e12aadf3b2">

**Comment by JohnZ9865** [comment]
![image](https://github.com/acm-ucr/senior-design-website/assets/64669569/be877080-5c7f-433a-a959-eb4789ee6e7d)
![image](https://github.com/acm-ucr/senior-design-website/assets/64669569/8164f274-b50a-4b7d-bf04-9148ebd39c85)
The page seems responsive for all screen sizes. The columns decrease as screen gets smaller, if that's what you're aiming for.
